apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-react
  template:
    metadata:
      labels:
        app: laravel-react
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: app
          image: <your-docker-hub-username>/<your-image-name>:<tag> # Replace with your actual image name and tag ex: vk42/laravel-react-app:1.0.7
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: laravel-env